name: myflix
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.0.0
  go_router: ^4.5.1
  cached_network_image: ^3.2.1
  freezed: ^2.1.1
  dio: ^4.0.6
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.7.0
  flutter_launcher_icons: ^0.12.0
  flutter_svg: 2.0.2
  overlay_support: ^2.1.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
    - assets/images/